spring:
  cloud:
    gateway:
      routes:
        - id: user-service-login
          uri: http://user-service
          predicates:
            - Path=/api/v1/users/login
          filters:
            - name: LoginFilter
        - id: user-service
          uri: http://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: AuthenticationFilter



